<?php
	return [
		'title' => 'Gastric Bypass',
		'subtitle' => 'Bariatric Surgery',
		'paragraph' => '<p>Gastric bypass surgery in Puerto Vallarta, Mexico and around the world is considered the Gold Standard for obesity treatment and related diseases such as diabetes, hypertension and dyslipidemia.</p>',
		'consiste_title'            => 'Benefits of Gastric Bypass Surgery as a Diabetes Treatment',
		'consiste_paragraph'        => '<p>Gastric bypass offers various health benefits for the short and the long term. In addition to losing weight and maintaining that weight loss, this type of surgery can help to control diabetes in > 90% of cases. Typically, among patients diagnosed with diabetes within 5 years of onset.</p><p>These results can even be achieved without using diabetes treatment medications, as long as you have adhered to a strict diet with and lifestyle and habit changes in addition to surgery.</p>',

		'factores_title' => 'QUESTIONS',
		'factores_paragraph' => '<p> <b>How much weight could I lose after Gastric Bypass surgery?</b><br /> Gastric bypass is a surgery with excellent weight loss results, achieving average rates of 80% weightless in the first 2 years, although many patients achieve this within the first 12 months. </p> <p> <b>What is Gastric Bypass?</b><br /> Gastric bypass surgery consists of making your stomach smaller in order to restrict your food intake and to bridge the intestines and alter the absorption of nutrients. If a patient has 6 meters of small intestine to absorb, then the bypass will use reduce that to an average of 3 to 4 meters which results in weight loss by two mechanisms: restriction and absorption. </p> <p> <b>How is Gastric Bypass performed and how long does the procedure take?</b><br /> This surgery is performed entirely by laparoscopy and the average surgical time is 2 hours. And the patient belongs two nights in hospital. </p> <p> <b>Will I need to take food supplements after Bypass Surgery?</b><br /> Due to the nature of gastric bypass and its high effectivity, it’s important to remember that you’ll need constant monitoring and follow-up visits with your surgeon and nutritionist. In addition to eating healthy you’ll need to supplement your diet with vitamins and minerals. </p> <p> <b>Am I eligible for Gastric Bypass?</b><br /> Recommended for people with a BMI of over 35 who have associated comorbidities (diabetes, hypertension, dyslipidemia, etc.) or a body mass index of over 40 with or without associated obesity comorbidities. </p> <p> In cases of bariatric surgery for patients with a BMI between 30 and 35 who also have diabetes, hypertension, or dyslipidemia, it can be feasible to perform the surgery if the patient’s health lends to the surgery.<br /> Bypass surgery is an excellent option for patients with obesity who also suffer from diseases associated with obesity and overweight.<br /> This surgery requires the surgeon and his team to have a broad understanding and mastery of laparoscopic surgical techniques in order to offer the patient the highest level of safety during their weight loss procedure. </p>',
	];
?>