<?php
	return [
		'title' => 'CMQ RIVIERA NAYARIT',
		'subtitle' => 'Hospitals',
		'paragraph' => '<p><b>CMQ Riviera Nayarit</b> offers the same quality, state-of-the-art care you’ve come to trust and expect at the hospital in <b>Puerto Vallarta</b>, now has a new, northern facility for those located in Bucerías, Punta Mita, or La Cruz de Huanacaxtle. </p> <p><b>CMQ Riviera Nayarit</b> is conveniently located just outside of <b>Puerto Vallarta</b>, in the heart of Bucerías, near the beautiful La Cruz de Huanacaxtle and the luxury resorts of Punta de Mita, you can rest assured that you will receive the most cutting edge medical care at the technologically-advanced CMQ Riviera Nayarit with our friendly, bilingual staff that will be present to attend to your every need. </p> <p>The <b>CMQ Riviera Nayarit</b> Hospital is an outstanding facility and we are proud to offer Gastric Sleeve and Gastric Bypass surgeries as well as other leading <b>weight loss surgeries</b> to our clients in this modern facility outside of <b>Puerto Vallarta</b>, Mexico. </p> <p>Nos gusta consentir a nuestros clientes en nuestras espectaculares nuevas instalaciones a las afueras de Puerto Vallarta, México. Contamos con:</p> <ul class="lista"> <li>Tecnologías médicas avanzadas</li> <li>Quirófanos de última generación</li> <li>Tecnología de vanguardia en todas las áreas</li> <li>Servicio de emergencias las 24 horas</li> <li>Personal médico certificado</li> <li>Laboratorio médico las 24 horas</li> <li>Servicio de tomografía computarizada (TAC) las 24 horas</li> <li>Hemodinámica</li> <li>Unidad de Cuidados Intensivos (UCI)</li> <li>Habitaciones cómodas y espaciosas</li> <li>Servicio de cafetería</li> </ul>',
		'instalacion' => 'HOSPITAL <span>FACILITIES</span>',
		'direccion' => '280 Av. Héroes de Nacozari Bucerías, Nayarit.',
		'mapa' => 'SEE MAP'
	];
?>