<?php
	return [
		'title' => 'Duodenal Switch',
		'subtitle' => 'Bariatric Surgery',
		'paragraph' => '<p>The Duodenal Switch performed by Dr. Sergio Del Hoyo in Puerto Vallarta, Mexico. It is also known as DS, BPD / DS, Biliopancreatic Division, and Duodenal Switch.</p><p>Duodenal Switch is a highly effective bariatric surgery, but very specific in its surgical indication and with very specific nutritional care.</p>',
		'consiste_title'            => 'Get real benefits',
		'consiste_paragraph'        => '<p>Having a duodenal switch as an obesity treatment has real benefits for you, such as a significant and more quick weight loss, compared with gastric band procedures and less chance of regaining weight, as well as more complete disappearance of obesity-related illnesses.</p>',

		'factores_title' => 'QUESTIONS',
		'factores_paragraph' => '<p> <b>Duodenal Switch Instructions</b><br> Duodenal Switch is recommended for patients with a BMI (body mass index) of more than 50, with or without diabetes or hypertension. The Duodenal Switch is a highly effective bariatric surgery for the control of diseases associated with obesity such as Diabetes, Hypertension and Dyslipidemia. </p> <p> <b>What is the Duodenal Switch?</b><br> This bariatric surgery has two steps which can be completed during one surgery or in two separate surgeries, depending on the health background and weight of the patient, in order to reduce surgical risks. <br> Duodenal Switch consists of creating a Gastric Sleeve (step 1) and then reducing the size of the stomach from 20% to 30% to restrict food intake. The second step of the process occurs in the intestines, reducing the length of intestines capable of absorbing fats and carbohydrates. In most cases, it’s possible to perform the complete 2-step process in one single surgery. This surgical procedure utilizes a food restriction as well as absorption mechanism in order to lose weight. </p> <p> <b>How the Duodenal switch surgery is performed?</b><br> Duodenal switch is performed laparoscopically and the average surgical time is 3 hours. The patient will stay 2 nights in the hospital. <br> The three-hour surgery is not recommended for patients with a high BMI, or who are considered high risk due to health conditions. In these instances, we recommend that the duodenal switch procedure is completed during two separate surgeries. The first surgery is the gastric sleeve procedure that will help the patient achieve enough weight loss for the second surgery. After 12 months have passed, the second surgery is performed on the intestines when the patient is in better health with a lower BMI. <p> <b>Will I require food supplements after a Duodenal Switch surgery?</b><br> For the duodenal switch procedure, it’s crucial to strictly adhere to the nutritional regimen given, including all necessary vitamins and supplements. Regularly scheduled follow-up visits to the surgeon and the nutritionist are also required for successful and healthy weight loss after surgery. </p>',
	];
?>