<?php
	return [
		'title' => 'Apendicitis',
		'subtitle' => 'Cirugía Gastrointestinal',
		'paragraph' => '<p>La apendicitis es cuando el apéndice, un pequeño saco que se encuentra adherido al intestino grueso, se inflama a causa de una obstrucción por heces o algún cuerpo extraño.</p> <p>La apendicitis es una condición grave y una causa muy común de cirugía de emergencia. </p>',
		'sintomas_title' => 'SÍntomas de la apendicitis',
		'sintomas_paragraph' => '<p>Los síntomas de la apendicitis son muy variables y puede ser difícil diagnosticarla en niños pequeños, ancianos y mujeres en edad fértil.</p><p>El primer síntoma a menudo es el dolor alrededor del ombligo. Este dolor al inicio normalmente es leve, pero después se vuelve más agudo y grave. Posiblemente también se presente falta de apetito, náuseas, vómitos y fiebre. </p><p>El dolor tiende a desplazarse a la parte inferior derecha del abdomen y a concentrarse en un punto directamente sobre el apéndice llamado el punto de McBurney. Esto ocurre con mayor frecuencia de 12 a 14 horas después del comienzo de la enfermedad. El dolor puede empeorar al caminar, toser o al hacer movimientos repentinos. </p><p>Los síntomas de la apendicitis que pueden presentarse después, son: escalofríos, temblores, estreñimiento o diarrea y vómitos. </p><p>Es muy importante acudir inmediatamente al médico al mostrar alguno de los síntomas de la apendicitis, pues si el apéndice llega a romperse, se puede presentar una peritonitis. </p>',
		'diagnostico_title' => 'Diagnóstico de la <span class="text-theme-color">apendicitis</span>',
		'diagnostico_paragraph' => '<p>Para que el médico pueda realizar un correcto diagnóstico de la apendicitis es importante que usted describa correctamente los síntomas que presenta. Asimismo, el médico debe hacer las siguientes pruebas:</p> <ul class="lista"> <li>Nivel de dolor: si usted tiene apendicitis, el dolor aumentará cuando el médico presione suavemente sobre el cuadrante inferior derecho del abdomen. Si el apéndice se ha roto, tocar el área del vientre puede causar mucho dolor. </li> <li>Exploración rectal: el médico puede tener un diagnóstico más acertado si encuentra sensibilidad en el lado derecho del recto. </li> <li>Examen de sangre: si esta prueba muestra un conteo alto de glóbulos blancos, puede sugerir que se presenta apendicitis. </li> <li>Estudios imagenológicos: una tomografía computarizada del abdomen y una ecografía abdominal pueden ayudar a tener un adecuado diagnóstico de la apendicitis. </li> </ul>',
	];
?>