<?php
	return [
		'title' => 'Bypass Gástrico RNY',
		'subtitle' => 'Cirugía Bariátrica',
		'paragraph' => '<p>La cirugía de Switch Duodenal es realizada por el Dr. Sergio Del Hoyo en Mexico, Puerto Vallarta . Es conocido también como (DS), (BPD/DS). (División biliopancreática, Switch Duodenal).<br>Es una cirugía altamente efectiva, pero muy específica en su indicación quirúrgica y con cuidados nutricionales, muy específicos.</p><p>El Switch Duodenal es una variación de otra cirugía bariátrica llamada desviación biliopancreática con excepción de que el Switch Duodenal deja una gran parte del estómago intacto, incluyendo la válvula pilórica, que se encarga de regular la liberación del contenido estomacal en el intestino delgado.</p>',
		'consiste_title'            => 'Beneficios de la cirugia de BYPASS GÁSTRICO y resolución de Diabetes ',
		'consiste_paragraph'        => '<p>El Bypass Gástrico ofrece beneficios a corto y a largo plazo, ya que además de lograr perder peso y mantener esa pérdida de peso, puede ayudar a controlar la diabetes en >90 % de los casos, principalmente aquellos aquellos pacientes con diagnóstico de diabetes < a 5 años de inicio.</p><p>Se logra incluso no utilizar medicamentos para tratar el diabetes, siempre que tenga apego a nutrición y cambio de hábitos, además de la cirugía.</p>',

		'factores_title' => 'PREGUNTAS',
		'factores_paragraph' => '<p> <b>¿Cuanto peso espero perder con cirugía de BYPASS GÁSTRICO?</b><br /> El Bypass Gástrico es una cirugía con resultados excelentes en la pérdida de peso, logrando tener tasas promedio de 80% de pérdida del exceso de peso en los primeros 2 años promedio, aunque la mayoría lo logra en los primeros 12 meses de la cirugía. </p> <p> <b>¿En que consiste el BYPASS GÁSTRICO?</b><br /> El Bypass Gástrico consiste en hacer un estómago pequeño para restringir la ingesta de alimento y hacer un puente en el intestino para alterar la absorción de nutrientes, es decir, si un paciente dispone de 6 metros de intestino delgado para absorber, entonces el Bypass utilizara un promedio de 3 a 4 metros para absorción y se pierda peso por dos mecanismos: restricción y absorción. </p> <p> <b>¿Como se realiza y cuanto tiempo dura la cirugía de BYPASS GÁSTRICO?</b><br /> Esta cirugía se realiza enteramente por laparoscopia y el tiempo quirúrgico promedio es de 2 horas. Y el paciente pertenece dos noches en hospital. </p> <p> <b>¿Requiere suplementos alimenticios?</b><br /> Es de suma importancia considerar que el paciente debido a las características de el procedimiento y su alta efectividad requiere de constante monitoreo y seguimiento por su Cirujano y Nutriólogo. Además de una buena alimentación deberá tener soporte de Vitaminas y  Minerales, y suplementos alimenticios. </p> <p> <b>¿Soy elegible para BYPASS GÁSTRICO?</b><br /> Esta indicado en personas con IMC > 35 asociado a comorbilidades( Diabetes, hitensión, dislipidemia, etc) o IMC, indice de masa corporal > 40 con comorbilidades o sin ellas.<br /> En caso de cirugia metabólica de pacientes con IMC entre 30 y 35 con diabetes, hipertension, dislipidemia es factible realizar la cirugia bajo lineamientos muy específicos de estudio del paciente. </p> <p> Es una excelente opción de tratamiento para pacientes con obesidad que además padecen enfermedades asociadas a la Obesidad de difícil manejo médico.<br /> Esta cirugía requiere de parte del cirujano y su equipo de amplio conocimiento y dominio de la técnica quirúrgica para ofrecer al paciente  seguridad en su procedimiento. </p>',
	];
?>