<?php
	return [
		'title' => 'Hernias',
		'subtitle' => 'Cirugía Gastrointestinal',
		'paragraph' => '<p>Una hernia es un saco formado por el revestimiento de la cavidad abdominal (peritoneo). El saco pasa a través de un agujero llamado fascia, que es un área débil en la capa fuerte de la pared abdominal que rodea el músculo.</p>',
		'tipos_title' => '¿QUÉ TIPOS DE <span class="text-theme-color">HERNIAS HAY?</span>',
		'tipos_paragraph' => '<p>Los tipos de hernias dependen de su ubicación:</p><ul class="lista"><li>Hernia femoral: es una protuberancia en la parte superior del muslo, justo debajo de la ingle. Este tipo es más común en las mujeres que en los hombres.</li><li>Hernia hiatal: se presenta en la parte superior del estómago. Se desarrolla cuando una porción de la parte superior del estómago se adentra en el tórax.</li><li>Hernia quirúrgica o eventración: si usted ha tenido una cirugía abdominal en el pasado, este tipo de hernia se puede dar a través de una cicatriz. </li><li>Hernia umbilical: es una protuberancia alrededor del ombligo. Sucede cuando el músculo alrededor del ombligo no se cierra completamente.</li><li>Hernia inguinal: es una protuberancia en la ingle. Este tipo es más común en los hombres y puede bajar hasta el escroto.</li></ul>',
		'causas_title' => 'CAUSAS DE LAS HERNIAS',
		'causas_paragraph' => '<p>Por lo regular no hay una causa clara para una hernia. Algunas veces se presentan por levantar objetos pesados, hacer esfuerzo al usar el baño o cualquier actividad que eleve la presión dentro del abdomen. Las hernias ocurren cuando hay una debilidad en la pared abdominal.</p> <p>Los bebés y los niños también pueden desarrollar hernias. Éstas pueden estar presentes al nacer, pero es posible que la protuberancia no sea notoria, ni que haya síntomas de hernia hasta más adelante en la vida. Aproximadamente 5 de cada 100 niños presentan hernias inguinales y son más comunes en los varones.</p> <p>Cualquier actividad o problema de salud que incremente la presión en el tejido y los músculos de la pared abdominal puede llevar a distintos tipos de hernias. Algunos pueden ser:</p> <ul class="lista"> <li>Estreñimiento crónico y pujar fuertemente para defecar.</li> <li>Tos crónica</li> <li>Fibrosis quística</li> <li>Agrandamiento de la próstata y esfuerzo para orinar</li> <li>Sobrepeso</li> <li>Líquido en el abdomen (ascitis)</li> <li>Levantar objetos pesados</li> <li>Diálisis peritoneal</li> <li>Desnutrición</li> <li>Tabaquismo</li> <li>Esfuerzo excesivo</li> <li>Criptorquidia</li> </ul><p>Las hernias también pueden ocurrir por antecedentes familiares.</p>',
		'sintomas_title' => 'SÍNTOMAS DE HERNIA',
		'sintomas_paragraph' => '<p>Generalmente no hay síntomas de hernia. Algunas personas presentan molestias o dolores que pueden empeorar al pararse, hacer esfuerzo o levantar objetos pesados. A medida que la hernia progresa, el síntoma más común es una protuberancia que es sensible y que está creciendo.</p><p>Cuando una hernia se agranda, puede quedar atrapada dentro del orificio y perder su riego sanguíneo, lo cual se denomina estrangulación. Los síntomas de hernia cuando un área del intestino ha perdido suministro de sangre incluyen náuseas y vómitos, y no ser capaz de eliminar gases o tener evacuaciones intestinales. Cuando esto sucede, se necesita una cirugía urgente.</p>',

 	];
?>