<?php
	return [
		'title' => 'Switch Duodenal',
		'subtitle' => 'Cirugía Bariátrica',
		'paragraph' => '<p>La cirugía de Switch Duodenal es realizada por el Dr. Sergio Del Hoyo en Mexico, Puerto Vallarta . Es conocido también como (DS), (BPD/DS). (División biliopancreática, Switch Duodenal).<br>Es una cirugía altamente efectiva, pero muy específica en su indicación quirúrgica y con cuidados nutricionales, muy específicos.</p><p>El Switch Duodenal es una variación de otra cirugía bariátrica llamada desviación biliopancreática con excepción de que el Switch Duodenal deja una gran parte del estómago intacto, incluyendo la válvula pilórica, que se encarga de regular la liberación del contenido estomacal en el intestino delgado.</p>',
		'consiste_title'            => 'Obtenga resultados reales',
		'consiste_paragraph'        => '<p>Al realizarse un Switch Duodenal como un tratamiento contra la obesidad, usted podrá obtener beneficios reales, tales como una significativa y rápida pérdida de peso, en comparación con la Banda Gástrica, así como menor posibilidad de recuperar el peso perdido y la desaparición de enfermedades relacionadas con la obesidad.</p>',

		'factores_title' => 'PREGUNTAS',
		'factores_paragraph' => '<p> <b>¿Indicaciones para la cirugía de Switch Duodenal?</b><br> Es indicada para pacientes con IMC (indice de masa corporal) >50 con o sin asociaciones a diabetes e hipertensión. El switch duodenal es una cirugía bariátrica altamente efectiva para el control de las enfermedades asociadas a la obesidad como Diabetes, Hipertensión y Dislipidemia. </p> <p> <b>¿En que consiste la cirugía de Switch Duodenal?</b><br> La cirugía tiene dos pasos, que se pueden hacer en un mismo tiempo quirúrgico o en dos tiempos quirúrgicos, dependiendo las características de salud y peso del paciente con el fin de disminuir riesgos quirurgicos.<br> Consiste en hacer una Manga Gástrica (paso 1) y reducir el tamaño del estómago a un 20 a 30% para hacer un efecto restrictivo de alimentos; el segundo paso es el proceso intestinal para la absorción de grasa y carbohidratos, reduciendo la cantidad de intestino capaz de Absorber nutrientes. Es posible realizar la cirugia completa en un solo tiempo quirúrgico la mayoría de la veces.Este procedimiento quirúrgico tiene mecanismo de restricción y absorción para perder peso. </p> <p> <b>¿Como se realiza la Cirugia de switch Duodenal?</b><br> Se realiza por laparoscopia y el tiempo quirúrgico promedio es de 3 horas. Permanece el paciente 2 noches en hospital. <br> En caso de pacientes con alto índice de obesidad, cuyo riesgo quirúrgico es alto y no es conveniente tardar tanto tiempo en cirugía es factible realizarlo en 2 tiempos, es decir: (1). Manga Gástrica lograr bajar suficiente peso y en 12 meses realizar el paso intestinal, con un paciente en mejores condiciones y mas seguras. </p> <p> <b>¿Requiero de suplementos alimenticios después de realizarme la cirugía de Switch Duodenal?</b><br> En esta cirugía es fundamental e indispensable el apego nutricional, suplementos, vitaminas, minerales y suplementos proteicos de por vida. <br> Así como seguimiento médico por su cirujano y Nutriologo. </p>',
	];
?>